languageCode = "en"
languageName = "English"
weight = 1
title = "Sander Ploegsma"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "My personal blog"
# copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "Sander Ploegsma"
image = "/img/avatar.jpg"
headline = "I like functional programming, code puzzles, cloud stuff and high-tech products."
bio = "I like functional programming, code puzzles, cloud stuff and high-tech products."
links = [
  #     { email = "mailto:hello@your_domain.com" },
  #     { link = "https://link-to-some-website.com/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/sanderploegsma" },
  { gitlab = "https://gitlab.com/sanderploegsma" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { keybase = "https://keybase.io/username" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://linkedin.com/in/sanderploegsma" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  #     { telegram = "https://t.me/username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/" },
  { x-twitter = "https://twitter.com/sanderploegsma" },
  #     { whatsapp = "https://wa.me/phone-number" },
  #     { youtube = "https://youtube.com/username" },
  #     { ko-fi = "https://ko-fi.com/username" },
]
