languageCode: en-us
baseUrl: https://www.sanderp.nl
theme: hello-friend
googleAnalytics: UA-35738635-2

params:
  showReadingTime: "true"
  contentTypeName: posts

languages:
  en:
    title: Sander Ploegsma

    params:
      logo:
        logoText: sander ploegsma
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: About me
          url: /about-me
