[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
GO_VERSION = "1.23.3"
HUGO_VERSION = "0.138.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
