[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
GO_VERSION = "1.22.1"
HUGO_VERSION = "0.123.7"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
